name: paisa
description: A expense manager app for Android, iOS, Web & Windows.

publish_to: "none"

version: 6.0.2+602

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animations: ^2.0.7
  chart_sparkline: ^1.0.13
  collection: ^1.17.0
  csv: ^5.0.1
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.3
  device_info_plus: ^9.1.2
  dynamic_color: ^1.6.5
  equatable: ^2.0.5
  file_picker: ^6.1.1
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  go_router: ^13.2.0
  go_router_builder: ^2.4.1
  google_fonts: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.0
  in_app_review: ^2.0.6
  in_app_update: ^4.1.4
  injectable: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.3
  material_color_utilities: ^0.5.0
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^5.0.1
  path_provider: ^2.0.11
  permission_handler: ^11.0.0
  provider: ^6.0.5
  quick_actions: ^1.0.7
  responsive_builder: ^0.7.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.2
  change_app_package_name: any
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.2.0+1
  freezed: ^2.4.6
  hive_generator: ^2.0.0
  import_sorter: ^4.6.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.7.1
  msix: ^3.7.0

dependency_overrides:
  #intl: ^0.18.0
  material_color_utilities: ^0.8.0

flutter_app_name:
  name: "Paisa"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  color_dark: "#121212"
  android: true
  ios: true
  android_12:
    image: assets/images/icon_light.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/icon_dark.png
    icon_background_color_dark: "#121212"

flutter_icons:
  ios: true
  android: false
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/ios_app_icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icon.png

msix_config:
  display_name: Paisa - Expense Tracker
  publisher_display_name: RetroMusic
  publisher: CN=22326927-E77C-435F-B91A-B9831883516E
  identity_name: 42423RetroMusic.Paisa-ExpenseTracker
  msix_version: "4.8.0.0"
  logo_path: C:\Users\Hemanth S\Documents\GitHub\flutter_expense\assets\images\icon.png
  capabilities: internetClient
  certificate_path: C:\Users\Hemanth S\Documents\paisa_certificate.pfx
  certificate_password: +h4Hem@nth$13+
  store: true
